name: proyecto-trazabilidad
services:
  backend:
    image: backend
    container_name: backend
    build:
      context: ./backend
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./backend:/backend
    environment:
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - FASTIFY_LOG_LEVEL=${FASTIFY_LOG_LEVEL}
      - FASTIFY_SECRET=${FASTIFY_SECRET}
      #- GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      #- GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    # tty: true
    user: 1000:1000
    working_dir: /backend
    ports:
      - 3000:3000

  frontend:
    image: frontend
    container_name: frontend
    command: sh -c "npm install && npm run start2"
    build:
      context: ./frontend
    volumes:
      - ./frontend/:/frontend
    ports:
      - 4200:4200
    #tty: true
    user: 1000:1000

  database:
    image: database
    container_name: database
    build:
      context: ./database
    volumes:
      - ./database/scripts/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
    ports:
      - 5436:5432

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy/proxy.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./proxy/certs:/etc/nginx/certs
    container_name: proxy
    depends_on:
      - frontend
      - backend
